name: CI

on:
  push:
    branches:
      - master

env:
  JENA_SHA512: ba2e966df3ff2c8727b02f95771aa9f9953687fadbd51a95fff3709bb342ca64c1ac54bc25c9e24432b038c14737979c48fad5885e5841d6c15cc4967859b037
  JENA_VERSION: 3.14.0
  MIRROR: http://www.eu.apache.org/dist/
  ARCHIVE: http://archive.apache.org/dist/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: sha512 checksum
      run: echo "$JENA_SHA512  jena.tar.gz" > jena.tar.gz.sha512
    - name: Download/check/unpack/move Jena in one go
      run: |
        wget -O jena.tar.gz $MIRROR/jena/binaries/apache-jena-$JENA_VERSION.tar.gz || \
        wget -O jena.tar.gz $ARCHIVE/jena/binaries/apache-jena-jena-$JENA_VERSION.tar.gz && \
        sha512sum -c jena.tar.gz.sha512 && \
        tar zxf jena.tar.gz && \
        rm jena.tar.gz*
    - name: generate other syntaxes for ontologies 
      run: for onto in *.ttl; do echo "Generate for ${onto%.*}"; for syntax in "RDF/XML rdf" "N-TRIPLE nt" "N3 n3" "JSON-LD jsonld"; do set -- $syntax; echo " - ${onto%.*}.$2"; apache-jena-3.14.0/bin/riot --output=$1 ${onto%.*}.ttl >> ${onto%.*}.$2 || echo "RIOT error" > ${onto%.*}.$2 ; done; done
    - name: delete jena
      run: rm -r apache-jena-$JENA_VERSION
    - name: delete hidden files
      run: rm -rf .* || true
    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: .
        
  
      
